force-app/main/default/objects/AWS_Keys__c/AWS_Keys__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>AWS_Keys</label>
</CustomObject>

force-app/main/default/objects/AWS_Keys__c/fields/AWS_AccessKey_Id__c.field-meta.xml
<CustomField>
    <fullName>AWS_AccessKey_Id__c</fullName>
    <label>AWS_AccessKey_Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AWS_Keys__c/fields/AWS_Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>AWS_Secret_Key__c</fullName>
    <label>AWS_Secret_Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AWSS3_GetService.cls
public class AWSS3_GetService extends AWS {
        public override void init() {
            AWS_Keys__c awsKeySet= AWS_Keys__c.getInstance('media.trex.test');
            String bucketName = awsKeySet.Name;
            accessKey = awsKeySet.AWS_AccessKey_Id__c;
            String secretKey = awsKeySet.AWS_Secret_Key__c;
            endpoint = new Url('https://'+bucketName+'.s3.amazonaws.com/');
            resource = '/';
            region = 'frankfurt';
            service = 's3';
            
            method = HttpMethod.XGET;
            //	Remember to set "payload" here if you need to specify a body
            //	payload = Blob.valueOf('some-text-i-want-to-send');
            //  This method helps prevent leaking secret key, 
            //  as it is never serialized
            createSigningKey(secretKey);
       }
       public String[] getBuckets() {
           HttpResponse response = sendRequest();
           String[] results = new String[0];
           // Read response XML; if we get this far, no exception happened
           // This code was omitted for brevity
           return results;
       }
}