force-app/main/default/objects/Health_professional__c/Health_professional__c.object-meta.xml
<CustomObject>
    <label>Health professional</label>
    <nameField>
        <label>Health professional</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Health professionals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Health_professional__c/fields/email__c.field-meta.xml
<CustomField>
    <fullName>email__c</fullName>
    <label>email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Health_professional__c/fields/first__c.field-meta.xml
<CustomField>
    <fullName>first__c</fullName>
    <label>first</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Health_professional__c/fields/last__c.field-meta.xml
<CustomField>
    <fullName>last__c</fullName>
    <label>last</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Health_professional__c/fields/Processed__c.field-meta.xml
<CustomField>
    <fullName>Processed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Processed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Health_professional_reference__c/Health_professional_reference__c.object-meta.xml
<CustomObject>
    <label>Health professional reference</label>
    <nameField>
        <label>Health professional reference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Health professional references</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Health_professional_reference__c/fields/Health_professional__c.field-meta.xml
<CustomField>
    <fullName>Health_professional__c</fullName>
    <label>Health professional</label>
    <referenceTo>Health_professional__c</referenceTo>
    <relationshipLabel>Health professional references</relationshipLabel>
    <relationshipName>Health_professional_references</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Health_professional_reference__c/fields/url__c.field-meta.xml
<CustomField>
    <fullName>url__c</fullName>
    <label>url</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Health_professional_reference__c/fields/words_cloud__c.field-meta.xml
<CustomField>
    <fullName>words_cloud__c</fullName>
    <label>words cloud</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Health_professional_reference_word_count__c/Health_professional_reference_word_count__c.object-meta.xml
<CustomObject>
    <label>Health professional reference word count</label>
    <nameField>
        <label>Health professional reference word count Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Health professional reference word cts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Health_professional_reference_word_count__c/fields/Health_professional_reference__c.field-meta.xml
<CustomField>
    <fullName>Health_professional_reference__c</fullName>
    <label>Health professional reference</label>
    <referenceTo>Health_professional_reference__c</referenceTo>
    <relationshipLabel>Health professional reference word cts</relationshipLabel>
    <relationshipName>Health_professional_reference_word_cts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/CovidIntegrationBatch.cls
global class CovidIntegrationBatch implements Database.Batchable<sObject>, Database.AllowsCallouts{

    private static final string query = 'SELECT ID, email__c, first__c, last__c,Processed__c FROM Health_professional__c WHERE Processed__c = False LIMIT 100';
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
     }
  
     global void execute(Database.BatchableContext BC,  List<sObject> scope){
        List<Health_professional_reference__c> referencesToUpsert = new List<Health_professional_reference__c>(); 
        for (Health_professional__c prof : (List<Health_professional__c>) scope){
            if (String.isNotBlank(prof.email__c) && String.isNotBlank(prof.first__c) && String.isNotBlank(prof.last__c)){
                CovidIntegrationCallout callout = new CovidIntegrationCallout();
                callout.doCallout(prof.email__c, prof.first__c, prof.last__c);
                //TODO: Guardar lo que esta en CovidIntegrationCallout.results
                //Health_professional_reference__c
                //TODO: Health_professional_reference_word_count__c
                Map<String, Health_professional_reference__c> mapReferences = new Map<String, Health_professional_reference__c> ();
                for(CovidIntegrationCallout.IntegrationResponse reference: callout.results){
                    Health_professional_reference__c referenceSF = new Health_professional_reference__c();
                    Map<String, Integer>  wordsCloud = reference.cloud;
                    referenceSF.url__c = reference.url;
                    String wordCloudsText = '';
                    for (String word: wordsCloud.keySet()){
                        wordCloudsText += word + ' : '+ wordsCloud.get(word) + ';';
                    }
                    referenceSF.words_cloud__c = wordCloudsText;
                    referenceSF.Health_professional__c = prof.Id;
                    referencesToUpsert.add(referenceSF);
                }
                
            }
            //try{
                
            /*}
            catch(Exception exc){
            }*/
        }      
        upsert referencesToUpsert;
        update scope;
     }
  
     global void finish(Database.BatchableContext BC){
     }
}